/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: '#09090b',
        surface: '#121214',
        'surface-2': '#1a1a1e',
        fg: '#f2f1ee',
        muted: '#9a9aa3',
        subtle: '#6b6b74',
        border: '#2a2a30',
        accent: '#d8d4cc',
        'accent-fg': '#0a0a0b',
        blue: '#8aa0b4',
        red: '#b08980',
        ok: '#7d9a7a',
        danger: '#c45c4a',
        chain: '#e8e4dc',
        gold: '#F2A900',
        'gold-dark': '#c48a00',
        teal: '#2fbaa4',
        'teal-dark': '#1c7c72',
        ocean: '#08090b',
        land: '#1c232c',
        ring: '#8aa0b4',
        'chloro-0': '#1c2e36',
        'chloro-1': '#1a4f54',
        'chloro-2': '#1c7c72',
        'chloro-3': '#2fbaa4',
        'chloro-4': '#7ee8d0',
        'net-testnet': '#f59e0b',
        'net-mainnet': '#16a765',
      },
      fontFamily: {
        display: ['Fraunces', 'serif'],
        sans: ['IBM Plex Sans', 'sans-serif'],
        mono: ['IBM Plex Mono', 'monospace'],
      },
      borderRadius: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        DEFAULT: '12px',
      },
    },
  },
  plugins: [],
}